const weatherCodes = {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Depositing rime fog",
  51: "Drizzle. Light intensity",
  53: "Drizzle. Moderate intensity",
  55: "Drizzle. Dense intensity",
  56: "Freezing Drizzle. Light intensity",
  57: "Freezing Drizzle. Dense intensity",
  61: "Rain. Slight intensity",
  63: "Rain. Moderate intensity",
  65: "Rain. Heavy intensity",
  66: "Freezing Rain. Light intensity",
  67: "Freezing Rain. Heavy intensity",
  71: "Snow fall. Slight intensity",
  73: "Snow fall. Moderate intensity",
  75: "Snow fall. Heavy intensity",
  77: "Snow grains",
  80: "Rain showers. Slight intensity",
  81: "Rain showers. Moderate intensity",
  82: "Rain showers. Violent intensity",
  85: "Snow showers. Slight intensity",
  86: "Snow showers. Heavy intensity",
  95: "Thunderstorm. Slight or moderate",
  96: "Thunderstorm with slight hail",
  99: "Thunderstorm with heavy hail",
};

const weatherIcons = {
  "0-day": "faSun",
  "0-night": "faMoon",
  "1-day": "faCloudSun",
  "1-night": "faCloudMoon",
  "2-day": "faCloudSun",
  "2-night": "faCloudMoon",
  "3-day": "faCloudSun",
  "3-night": "faCloudMoon",
  45: "faSmog",
  48: "faSmog",
  51: "faCloudRain",
  53: "faCloudRain",
  55: "faCloudRain",
  56: "faCloudRain",
  57: "faCloudRain",
  61: "faCloudShowersHeavy",
  63: "faCloudShowersHeavy",
  65: "faCloudShowersHeavy",
  66: "faCloudShowersHeavy",
  67: "faCloudShowersHeavy",
  71: "faSnowflake",
  73: "faSnowflake",
  75: "faSnowflake",
  77: "faSnowflake",
  80: "faCloudShowersHeavy",
  81: "faCloudShowersHeavy",
  82: "faCloudShowersHeavy",
  85: "faSnowflake",
  86: "faSnowflake",
  95: "faCloudBolt",
  96: "faCouldMeatball",
  99: "faCouldMeatball",
};

export { weatherCodes, weatherIcons };
